# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Neo's works
subtitle:
description:
author: Neo Alienson
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://neo.works
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: material
theme: hueman

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
    path: sitemap.xml

# https://github.com/liuzc/hexo-autonofollow
nofollow:
  enable: true
  exclude:

# https://github.com/hexojs/hexo-browsersync
browsersync:
  logLevel: "warn"
  ghostMode:
    scroll: true

# https://github.com/chenzhutian/hexo-all-minifier
all_minifier: false
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false

# https://www.npmjs.com/package/hexo-renderer-markdown-it-plus
# Default enable plugins:
# markdown-it-katex
markdown_it_plus:
    highlight: true
    # html is required for the flowchart and sequence diagram
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer: true
    quotes: “”‘’
    pre_class: highlight
    plugins:
        - plugin:
            name: markdown-it-abbr
            enable: true
        - plugin:
            name: markdown-it-footnote
            enable: true
        - plugin:
            name: markdown-it-ins
            enable: false
        - plugin:
            name: markdown-it-emoji
            enable: true
        - plugin:
            name: markdown-it-deflist
            enable: false
        - plugin:
            name: markdown-it-toc-and-anchor
            enable: true
        - plugin:
            name: markdown-it-sub
            enable: true
        - plugin:
            name: markdown-it-sup
            enable: true
        - plugin:
            name: markdown-it-mark
            enable: false
